services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      target: builder # マルチステージビルドの場合、ビルド対象を指定
    command:
      - ./main
    container_name: backend
    env_file: './backend/.env'
    ports:
      - "8080:8081"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=difflog
    depends_on:
      - db

  frontend:
    build: ./frontend/ShareTube
    container_name: frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true

  db:
    image: mysql:8.0
    container_name: db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: video_sns
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  node_modules:
