services:
  backend:
    build:
      context: ./backend # ディレクトリ名
      dockerfile: ./Dockerfile
      target: builder # マルチステージビルドの場合、ビルド対象を指定
    command:
      - ./main
    container_name: difflog_backend
    env_file: './backend/.env'
    ports:
      - "8080:8081"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=difflog
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: difflog
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  node_modules: